Count executions by installation method
fastlane/refresher pull request #19
Opened 2016-12-06 21:28 UTC by ohwutup

2016-12-06 21:31 UTC, ohwutup commented on db/schema.rb
> +  enable_extension "pg_stat_statements"
Not totally sure how these ended up here? Going to look more into this.

2016-12-06 21:41 UTC, KrauseFx requested changes

2016-12-06 21:41 UTC, KrauseFx commented on db/schema.rb
> +  enable_extension "pg_stat_statements"
Might be related to your Postgres version? It's probably save to just delete them

2016-12-06 21:41 UTC, KrauseFx commented on db/schema.rb
> +    t.integer  "install_method_standalone", default: 0
You have to commit the migration file, not just the updated schema 👍

2016-12-06 21:50 UTC, ohwutup commented on db/schema.rb
> +    t.integer  "install_method_standalone", default: 0
ohhhh. hmm. I didn't realize they didn't get committed there... I had to do a couple of migrations to get it right. Do you know how I should do that?

2016-12-07 19:12 UTC, KrauseFx approved these changes

2016-12-07 19:12 UTC, KrauseFx commented on db/migrate/20161207145632_add_installation_method_to_bacons.rb
> +    add_column :bacons, :install_method_standalone, :integer, default: 0
Beautiful pre-fix and default values 👍

2016-12-07 19:21 UTC, merged